<?xml version="1.0" encoding="UTF-8" standalone="no"?><testsuite errors="0" failures="1" name="Importar registros no llames" skipped="0" tests="1" time="27.22" timestamp="2023-03-08 12:23:58"><testcase name="Importar un archivo con datos invalidos"><failure message="&#10;Expecting a value that contains: &lt;[number_already_exists]&gt;&#10;But got........................: &lt;&quot;&quot;&gt;" type="java.lang.AssertionError">
Expecting a value that contains: &lt;[number_already_exists]&gt;
But got........................: &lt;""&gt;</failure><system-err>
Expecting a value that contains: &lt;[number_already_exists]&gt;
But got........................: &lt;""&gt;&#13;
co.com.arbusta.certification.expand.interactions.errorListTable.verificarErroresTabla(errorListTable.java:18)&#13;
co.com.arbusta.certification.expand.stepdefinitions.administration.basic.noCallRegister.importNoCallRegister_Steps.la_seccion_permite_descargar_el_archivo_de_errores(importNoCallRegister_Steps.java:90)&#13;
io.cucumber.java.Invoker.doInvoke(Invoker.java:66)&#13;
io.cucumber.java.Invoker.invoke(Invoker.java:24)&#13;
io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)&#13;
io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)&#13;
io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)&#13;
io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)&#13;
io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)&#13;
io.cucumber.core.runner.TestStep.run(TestStep.java:57)&#13;
io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)&#13;
io.cucumber.core.runner.TestCase.run(TestCase.java:95)&#13;
io.cucumber.core.runner.Runner.runPickle(Runner.java:75)&#13;
io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:151)&#13;
io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)&#13;
io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:151)&#13;
io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)&#13;
io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)&#13;
io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)&#13;
io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:258)&#13;
io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:58)&#13;
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
</system-err></testcase></testsuite>