<?xml version="1.0" encoding="UTF-8" standalone="no"?><testsuite errors="0" failures="2" name="Importar registros no llames" skipped="0" tests="7" time="81.41" timestamp="2023-04-14 05:45:21"><testcase name="Importar un archivo con formato invalido"/><testcase name="Importar un archivo con columnas faltantes"/><testcase name="Importar un archivo con columnas repetidas"/><testcase name="Importar un archivo con columnas extras"><failure message="&#13;&#10;Expected: an element that is visible&#13;&#10;     but: no matching element found by [RELLENAR located with: //span[contains(text(),'Columna no permitida:')]]" type="java.lang.AssertionError">&#13;
Expected: an element that is visible&#13;
     but: no matching element found by [RELLENAR located with: //span[contains(text(),'Columna no permitida:')]]</failure><system-err>&#13;
Expected: an element that is visible&#13;
     but: no matching element found by [RELLENAR located with: //span[contains(text(),'Columna no permitida:')]]&#13;
co.com.arbusta.certification.expand.stepdefinitions.administration.basic.noCallRegister.importNoCallRegister_Steps.el_mensaje_indica_que_el_archivo_no_puede_ser_importado(importNoCallRegister_Steps.java:70)&#13;
âœ½.El mensaje indica que el archivo no puede ser importado(classpath:features/administration/basic/noCallRegister/importNoCallRegisters.feature:25)&#13;
</system-err></testcase><testcase name="Importar un archivo con columnas sin nombre"/><testcase name="Importar un archivo con datos invalidos"><failure message="&#10;Expecting a value that contains: &lt;[number_already_exists]&gt;&#10;But got........................: &lt;&quot;attribute_missing_prefix&quot;&gt;" type="java.lang.AssertionError">
Expecting a value that contains: &lt;[number_already_exists]&gt;
But got........................: &lt;"attribute_missing_prefix"&gt;</failure><system-err>
Expecting a value that contains: &lt;[number_already_exists]&gt;
But got........................: &lt;"attribute_missing_prefix"&gt;&#13;
co.com.arbusta.certification.expand.interactions.errorListTable.verificarErroresTabla(errorListTable.java:18)&#13;
co.com.arbusta.certification.expand.stepdefinitions.administration.basic.noCallRegister.importNoCallRegister_Steps.la_seccion_permite_descargar_el_archivo_de_errores(importNoCallRegister_Steps.java:90)&#13;
io.cucumber.java.Invoker.doInvoke(Invoker.java:66)&#13;
io.cucumber.java.Invoker.invoke(Invoker.java:24)&#13;
io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)&#13;
io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)&#13;
io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)&#13;
io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)&#13;
io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)&#13;
io.cucumber.core.runner.TestStep.run(TestStep.java:56)&#13;
io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)&#13;
io.cucumber.core.runner.TestCase.run(TestCase.java:84)&#13;
io.cucumber.core.runner.Runner.runPickle(Runner.java:75)&#13;
io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:130)&#13;
io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)&#13;
io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:130)&#13;
io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)&#13;
io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)&#13;
io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)&#13;
io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:259)&#13;
io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:59)&#13;
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
</system-err></testcase><testcase name="Importar un archivo con datos validos"/></testsuite>